name: 'release confirmation action'
description: 'This action is used to detect releases from Github pull request labels.'
inputs:
  # require params(common)
  githubToken:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  action:
    description: 'entrypoint(merged|released|notify)'
  mergedLabel:
    description: 'After merged label'
    default: 'action-merged'
  releasedLabel:
    description: 'After released label'
    default: 'action-released'
  # optional params(common)
  isDebug:
    description: 'debug mode(disable:0, enable:1)'
    default: '0'
  # require params(action = merged, released)
  baseUrl:
    description: 'Base URL for GitHub API'
    default: "https://api.github.com/repos"
  repo:
    description: '{owner}/{repo}'
    default: "${{ github.repository }}"
  number:
    description: 'pull_request number'
    default: "${{ github.event.pull_request.number }}"
  # require params(action = notify)
  slackWebhook:
    description: 'SLACK_WEBHOOK'
  notifySubject:
    description: 'Title to notify Slack'
    default: 'List of pull requests that have not been released.'
  channel:
    description: 'Set slack channel(e.g. #random)'
    default: '#random'
  unreleasedPullsSubject:
    description: 'Slack Section Subject.'
    default: 'There are pull requests that have not been released.'
  # optional params(action = notify)
  mention:
    description: 'Set slack user_id(e.g. <@USER_ID>|<!here>|<!channel>)'
    default: ''
  showReleasedPulls:
    description: 'notify released pulls(disable:0, enable:1)'
    default: '0'
  releasedPullsSubject:
    description: 'Slack Section Subject.'
    default: 'Here is a list of recently released pull requests.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.baseUrl }}
    - ${{ inputs.repo }}
    - ${{ inputs.number }}
  env:
    GITHUB_TOKEN: ${{ inputs.githubToken }}
    SLACK_WEBHOOK: ${{ inputs.slackWebhook }}
    DEBUG_MODE: ${{ inputs.isDebug }}
    SUBJECT: ${{ inputs.notifySubject }}
    MENTION: ${{ inputs.mention }}
    CHANNEL: ${{ inputs.channel }}
    MERGED_LABEL: ${{ inputs.mergedLabel }}
    RELEASED_LABEL: ${{ inputs.releasedLabel }}
    SHOW_RELEASED_PULLS: ${{ inputs.showReleasedPulls }}
    UNRELEASED_PULLS_SUBJECT: ${{ inputs.unreleasedPullsSubject }}
    RELEASED_PULLS_SUBJECT: ${{ inputs.releasedPullsSubject }}
