name: 'release confirmation action'
description: 'This action is used to detect releases from Github pull request labels.'
inputs:
  githubToken:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  action:
    description: 'entrypoint(merged|released|notify)'
  baseUrl:
    description: ''
    default: "https://api.github.com/repos"
  repo:
    description: 'owner/repo'
    default: "${{ github.repository }}"
  number:
    description: 'pull_request number'
    default: "${{ github.event.pull_request.number }}"
  mergedLabel:
    description: 'after merged label'
    default: 'action-merged'
  releasedLabel:
    description: 'after released label'
    default: 'action-released'
  mergedLabelColor:
    description: 'label color(default: #ffcc99)'
    default: '#ffcc99'
  releasedLabelColor:
    description: 'label color(default: #ffcc99)'
    default: '#ffcc99'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.baseUrl }}
    - ${{ inputs.repo }}
    - ${{ inputs.number }}
    - ${{ inputs.mergedLabel }}
    - ${{ inputs.releasedLabel }}
    - ${{ inputs.mergedLabelColor }}
    - ${{ inputs.releasedLabelColor }}
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    SLACK_API_TOKEN: ${{ inputs.slack-api-token }}
