name: 'release confirmation action'
description: 'This action is used to detect releases from Github pull request labels.'
inputs:
  action:
    description: 'entrypoint(merged|released|notify)'
  mergedLabel:
    description: 'after merged label'
    default: 'action-merged'
  releasedLabel:
    description: 'after released label'
    default: 'action-released'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.mergedLabel }}
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    SLACK_API_TOKEN: ${{ inputs.slack-api-token }}
